### PR TITLE
More precise coin flip

### PR DESCRIPTION
**Pull request by andersontr15**
More precise coin flip

### CODE REVIEW

**Comment by EvanHahn** [comment]
How is this more precise?

**Comment by andersontr15** [comment]
Yeah on second thought I guess you're right. Math.random() returns a value between 0 and 0.99 so I guess it will never truly be even.

**Comment by EvanHahn** [comment]
Sounds good. Do you mind if I close this?

**Comment by andersontr15** [comment]
Yeah sure. Just finished reading your book on Express. Good book man.

**Comment by EvanHahn** [comment]
Aw, thanks! Hope it can help in some small way.

**Comment by andersontr15** [comment]
Yeah no problem. Sorry to keep commenting on the thread, but would you be down to interview on my channel sometime? I make daily coding videos. 

https://www.youtube.com/channel/UCFhC3Z6_9zjsxfBADZ-CEEg

**Comment by EvanHahn** [comment]
Shoot me an email at me@evanhahn.com and we can talk further!

**Pull request closed without merging**
