### PR TITLE
ES6ifiy and refactor

### PR DESCRIPTION
**Pull request by garritfra**

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks for submitting! I'll take a look at this soon.

**Review by EvanHahn — CHANGES_REQUESTED** [review]
I'm hesitant to accept this because it's a breaking change. It'll break the `<script>` tag integration (because `module.exports` won't be defined) and it'll also break in environments that don't support these newer JavaScript features.

I like the changes in the readme because I assume people are using ES6+ nowadays, but I'm hesitant to make a breaking change here.

What do you think?

**Comment by garritfra** [comment]
That's a great point. I haven't thought about this before. I'm still relatively new to the open source js community and I don't have the proper knowledge to spot weakpoints like this. Thanks for pointing that out! 

One thing though. Would it make a difference to rewrite the original function export

```js
if (typeof module !== 'undefined') {
  module.exports = coinflip;
}
```
To this?
```js
if (typeof module !== "undefined") {
  module.exports = function() {
    return Math.random() < 0.5;
  }
}
```

In case you're wondering, i'll redo the commit entirely because I deleted my fork😬

**Comment by EvanHahn** [comment]
There are two differences between those examples, one much bigger than the other:

1. If `module.exports` is defined, there isn't a functional difference between the two. But if it's not defined (like when using a `<script>` tag), it won't work, and `coinflip` won't be available. For example, this won't work:

   ```html
   <script src="coinflip.js"></script>
   <script>
     console.log(coinflip());
   </script>
   ```

2. A smaller change: the [name of the function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) will be missing in the second example, which is sometimes helpful when debugging. You could fix that with something like this:

   ```javascript
   module.exports = function coinflip () {
      // ...
   }
   ```

Because you're thinking of redoing this, do you mind if I close this pull request?

**Comment by garritfra** [comment]
Okay then, I'll leave the module as is and just update the readme

**Pull request closed without merging**
